- assets/javascripts/map/index.js
- assets/javascripts/map/map-config.json
- assets/javascripts/map/map.js
- assets/sass/map/_nav.scss
- assets/sass/map/index.scss
- assets/sass/map/overlay.scss
- bin/build
- bin/build-js-map
- bin/copy-assets
- config/index.js
- config/schema.js
- config/server.example.json
- config/server.json
- package.json
- server/models/errors.json
- server/models/maps-view.js
- server/routes/home.js
- server/routes/index.js
- server/routes/os-get-capabilities.js
- server/routes/search.js
- server/services/address.js
- server/util.js
- server/views/home.html
- server/views/map.html
> Initial Alpha prototype work

- config/schema.js
- config/server.json
- index.js
- package.json
- server/manifest.js
- test/config.js
> errbit implementation

- client/sass/map/index.scss
- server/views/summary.html
FMfP: Remove full screen / exit full screen icon and feature from the MOBILE VIEW of the Flood Risk Summary screen
https://eaflood.atlassian.net/browse/FLO-1653
> FLO-1653 Remove full screen in mobile

- bin/copy-gov
- config/README.md
- config/schema.js
- config/server.json
- server/views/partials/bodyEnd.html
https://eaflood.atlassian.net/browse/FLO-1655
> FLO-1655: Activate Google Analytics

- server/views/index.js
https://eaflood.atlassian.net/browse/FLO-1628
> FLO-1628: Implement correct name for service

- server/routes/feedback.js
- server/routes/index.js
- server/views/feedback.html
https://eaflood.atlassian.net/browse/FLO-1622
> FLO-1622: Feedback survey

- server/views/home.html
Implement content changes to screen 1 - Search for development location
https://eaflood.atlassian.net/browse/FLO-1682
> FLO-1682: Implement content changes to screen 1

- client/sass/confirm-location/index.scss
- server/views/confirm-location.html
Implement content changes to screen 2 - Confirm development location
https://eaflood.atlassian.net/browse/FLO-1684
> FLO-1684: Implement content changes to screen 2

- bin/build-js
- client/js/index.js
- client/sass/application.scss
- client/sass/summary/index.scss
- package.json
- server/views/confirm-location.html
- server/views/partials/head.html
- server/views/partials/summary/area-benefiting.html
- server/views/partials/summary/zone1.html
- server/views/partials/summary/zone2.html
- server/views/partials/summary/zone3.html
- server/views/summary.html
Implement content changes to screen 3 - Flood Risk Summary screen
https://eaflood.atlassian.net/browse/FLO-1685
> FLO-1685: Implement content changes to screen 3

- server/views/not-england.html
Implement correct name for service across product and links to it
https://eaflood.atlassian.net/browse/FLO-1628
> FLO-1628: Implement correct name for service across product

- client/sass/application.scss
- client/sass/confirm-location/index.scss
- server/routes/confirm-location.js
- server/services/address.js
- server/views/confirm-location.html
- test/routes/confirm-location.js
https://eaflood.atlassian.net/browse/FLO-1617
> FLO-1617: Special characters in search return 404 service not available

- server/views/home.html
- server/views/partials/summary/area-benefiting.html
- server/views/partials/summary/zone1.html
- server/views/partials/summary/zone2.html
- server/views/partials/summary/zone3.html
FLO-2041 FMfP - Google Analytics tagging
> Google Analytics tagging

- client/js/map-config.json
- server/routes/pdf.js
> New layer settings

- docs/release-1.2.0/fmp-release1.2.0.txt
- package-lock.json
- package.json
- server/routes/pdf.js
- server/views.js
- Data release
- Fix pdf timestamp (feature/FCRM-505)
> Release 1.2.0

- package.json
- server/views/partials/bodyEnd.html
Can you review the code changes please?
> done changes as per CO for google Analytics

- docs/release-1.2.8/fmp-release1.2.8.txt
- package.json
Please could you review the latest data release?
> Release 1.2.8 data update

- config/server.example.json
- docs/release-1.3.2/fmp-release1.3.2.txt
- package.json
- server/views/not-england.html
- test/models/page-headers.js
- Broken links on not england page
- Text update
- OS Map API env variables update
> Merge current development branch to master

- server/views/not-england.html
- Remove word "risk" from not england text
> FCRM-2651-removed word risk

- client/js/map.js
- client/sass/_map.scss
- client/sass/confirm-location/index.scss
- client/sass/summary/index.scss
- docs/release-1.3.3/fmp-release1.3.3.txt
- package.json
- server/views/confirm-location.html
- server/views/summary.html
Merging the os copyright changes into develop branch.
> modified map copyright statement

- server/views/partials/printDialog.html
> FCRM-3601 added missing govuk-button class to printDialog Download button

- server/views/confirm-location.html
This was fixed already by @Harsh291104 but was wiped, presumably by mistake, by a later commit/merge by hari. I've skipped a review as it is reinstating an already reviewed change.
> FCRM-3191 - reinstate fix for confirm location on mobile pages

- client/js/confirm-location/index.js
- client/js/map-utils.js
- server/routes/404.js
- server/routes/maintenance.js
- test/client/map-utils-no-session-storage.js
- test/client/map-utils.js
Some additional tests to improve coverage of the client side map code
> FCRM-3731 added tests to cover mapUtils.mapState

- client/js/map.js
This reverts commit 6e8eb23ea3e01a3742e9707e961c89df7c7c99eb.
> FCRM-3771 Revert "FCRM-2575 remove restriction on map zoom levels"

- client/js/map.js
This reverts commit 82cef11f482825a8fcbc7572b3a08490dbbb9e3c.
> FCRM-2575 reinstate the increased map zoom levels

- client/js/confirm-location/index.js
- client/js/vector-drag.js
- client/sass/confirm-location/index.scss
- server/routes/flood-zone-results.js
- server/views/confirm-location.html
- test/models/page-headers.js
- test/routes/confirm-location.js
- test/routes/flood-zone-results.js
This reverts commit 779e6acbeb316b6fd5b406b044a21b9981563b67.
I have left the code that will go back when this revert is reverted in place but commented out. I think this will help avoid merge conflicts when we undo this revert.
> FCRM-3877 Revert "FCRM-3773 Made the confirm-location map Boundary Only"

- .gitignore
- package-lock.json
- package.json
- server/views/check-your-details.html
- server/views/layout.html
- server/views/os-terms.html
- test/routes/home.js
- test/routes/os-terms.js
NB this PR was forked off FCRM-5177, so I could deploy both features so you will also see the changes for that PR
> FCRM-5177 - check-your-details - added extra text and changed request to order

- client/js/defra-map/index.js
Commented out code is left in deliberately as they keep changing their minds about what to show and/or hide
> FCRM-5489 replaced depth colours for SW and removed SW CC layers

- server/routes/__tests__/__snapshots__/home.spec.js.snap
- server/views/home.html
> Revert "FCRM-5774 - moving start button to below before you start section"

- server/routes/__tests__/__snapshots__/how-to-use-flood-map-for-planning-data.spec.js.snap
- server/views/how-to-use-flood-map-for-planning-data.html
- server/views/partials/surface-water-suitability.html
https://eaflood.atlassian.net/browse/FCRM-6356
Update to content on how to use flood data page.
> FCRM-6356 How to use flood data page content update
